name: AI Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "**.php"
      - "**.yml"

jobs:
  gpt-review:
    if: contains(github.event.*.labels.*.name, 'gptReview')
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Japanese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4
          PROMPT: |
            あなたは非常に経験豊富なソフトウェアエンジニアです。回答は日本語でお願いします。
            以下の指針に従い、コードのレビューを行ってください。

            ### レビューの目的
            1. コード品質を向上させること。
            2. 修正が必要な箇所を指摘し、改善案を提供すること。
            3. 優れた箇所を挙げて、開発者を称賛すること。

            ### レビューの指針
            以下の項目に基づいてレビューを行ってください：
            - **ロジック**: 誤解を招く、または非効率的なロジックがないか。
            - **セキュリティ**: 潜在的なセキュリティリスク（例: SQLインジェクション、XSS）。
            - **パフォーマンス**: リソース効率が良いか、無駄がないか。
            - **保守性**: コードが読みやすく、一貫性があり、将来的な拡張に対応できるか。
            - **モジュール性**: コードが適切に分割され、再利用可能であるか。
            - **ベストプラクティス**: 以下の設計原則を守っているか確認してください：
              - **DRY（Don't Repeat Yourself）**: 冗長なコードを排除。
              - **SOLID原則**: 単一責任、オープン/クローズド原則、依存関係逆転など。
              - **KISS（Keep It Simple, Stupid）**: 複雑さを排除し、シンプルに設計。
              - **YAGNI（You Aren't Gonna Need It）**: 過剰な機能を追加していないか。

            ### レビューの注意点
            - 提案は、修正の理由を説明した上で、変更後のコード例を含めてください。
            - **WHAT**（動作内容）を表すコメントの指摘は控えめにしてください。
            - 未定義のクラスやメソッドについての指摘は控えめにしてください。

            ### レビュー形式
            レビュー結果を以下の形式で提供してください：

            - **全体概要**: レビュー対象の変更に関する簡潔な要約。
            - **優れた点**: 優れた設計、パフォーマンス、または保守性の観点で評価できる箇所を挙げてください。
            - **改善提案**: 問題点を特定し、変更理由と具体的なコード例を示してください。

          top_p: 1
          temperature: 1
          max_tokens: 4096
          MAX_PATCH_LENGTH: 4096
